"use client";
import { useMemo, useState, useTransition } from "react";
import { generateCampaoTeams, getCampaoBalanceScore, getCampaoTeamStats, moveCampaoPlayer, type CampaoCategory, type CampaoPlayer, type CampaoRelationship, type CampaoState, type CampaoTeam } from "@/lib/campao-team-balancer";
import { deleteCampaoRelationship, saveCampaoRelationship, saveCampaoSimulation } from "./actions";

type Props = { persistenceUnavailable: boolean; players: (CampaoPlayer & { category: CampaoCategory })[]; relationships: (CampaoRelationship & { category: CampaoCategory })[]; simulations: { id: string; category: CampaoCategory; name: string; teams: unknown; balanceScore: number; updatedAt: string }[] };
const positionLabel: Record<string, string> = { GOLEIRO: "Goleiro", ZAGUEIRO: "Zagueiro", LATERAL: "Lateral", VOLANTE: "Volante", MEIA: "Meia", ATACANTE: "Atacante" };
const relationshipTypeLabel: Record<string, string> = { FATHER_AND_SON: "Pai e filho", BROTHERS: "Irmãos", FAMILY: "Família", FRIENDS: "Amigos", SPECIAL_REQUEST: "Pedido especial", OTHER: "Outro" };
export function CampaoSimulationClient({ persistenceUnavailable, players: allPlayers, relationships: allRelationships, simulations }: Props) {
  const [category, setCategory] = useState<CampaoCategory>("ADULTO"); const [dragged, setDragged] = useState<string | null>(null); const [isPending, startTransition] = useTransition();
  const players = useMemo(() => allPlayers.filter(p => p.category === category), [allPlayers, category]);
  const relationships = useMemo(() => allRelationships.filter(r => r.category === category), [allRelationships, category]);
  const [state, setState] = useState<CampaoState>({ players: allPlayers.filter(p => p.category === "ADULTO"), relationships: allRelationships.filter(r => r.category === "ADULTO"), teams: [] });
  const current = state.players === players ? state : { ...state, players, relationships };
  const score = getCampaoBalanceScore(current); const assigned = new Set(current.teams.flatMap(t => t.playerIds));
  const playersWithoutLevel = players.filter((player) => !player.level);
  function switchCategory(next: CampaoCategory) { setCategory(next); setState({ players: allPlayers.filter(p => p.category === next), relationships: allRelationships.filter(r => r.category === next), teams: [] }); }
  function save() { startTransition(() => { void saveCampaoSimulation({ category, name: `Simulação ${category === "ADULTO" ? "Adulto" : "Master"}`, teams: current.teams, statistics: current.teams.map(t => getCampaoTeamStats(current, t)), balanceScore: score }); }); }
  return <main className="xv-page-shell"><div className="xv-page-container space-y-5">
    <section className="xv-card"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8B6914]">Campeonato Interno XV Campão 2026</p><h1 className="mt-2 text-3xl font-black text-[#101010]">Simulação avançada de times</h1><p className="mt-2 max-w-3xl text-sm text-[#4B5563]">Geração multiobjetivo por posição, nível, idade e vínculos. Os cálculos ocorrem localmente; salve apenas as simulações que quiser manter.</p></div>
      <div className="mt-5 flex gap-2"><button onClick={() => switchCategory("ADULTO")} className={`rounded-xl px-4 py-2 font-bold ${category === "ADULTO" ? "bg-[#B89020] text-white" : "border"}`}>Adulto</button><button onClick={() => switchCategory("MASTER")} className={`rounded-xl px-4 py-2 font-bold ${category === "MASTER" ? "bg-[#B89020] text-white" : "border"}`}>Master</button><button disabled={playersWithoutLevel.length > 0} title={playersWithoutLevel.length ? "Defina o nível de todos os inscritos antes de sortear." : undefined} onClick={() => setState(generateCampaoTeams(current))} className="ml-auto rounded-xl bg-[#101010] px-4 py-2 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Gerar nova simulação</button><button disabled={persistenceUnavailable || !current.teams.length || isPending} onClick={save} className="rounded-xl bg-[#B89020] px-4 py-2 font-bold text-white">Salvar simulação</button></div>
    </section>
    {persistenceUnavailable ? <div className="rounded-xl border border-[#FDBA74] bg-[#FFF7ED] px-4 py-3 text-sm text-[#9A3412]">A estrutura de persistência ainda não foi aplicada ao banco. A simulação pode ser usada, mas vínculos e simulações salvas só estarão disponíveis após a migration.</div> : null}
    {playersWithoutLevel.length > 0 ? <div className="rounded-xl border border-[#FDBA74] bg-[#FFF7ED] px-4 py-3 text-sm text-[#9A3412]">{playersWithoutLevel.length} {playersWithoutLevel.length === 1 ? "jogador está sem nível" : "jogadores estão sem nível"}. Eles aparecem na lista e podem receber vínculos, mas o sorteio fica liberado somente após classificar todos.</div> : null}
    <section className="grid gap-3 sm:grid-cols-4">{[["Inscritos", players.length], ["Times", current.teams.length], ["Score", `${score}/100`], ["Salvas", simulations.filter(s => s.category === category).length]].map(([l,v]) => <div key={String(l)} className="xv-card"><p className="text-xs font-bold uppercase text-[#6B7280]">{l}</p><p className="mt-1 text-2xl font-black">{v}</p></div>)}</section>
    <section className="xv-card"><h2 className="text-xl font-black">Inscritos da categoria</h2><p className="mt-1 text-sm text-[#6B7280]">A lista completa fica disponível para consulta e criação de vínculos, inclusive antes da classificação de nível.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{players.map(player => <PlayerCard key={player.id} player={player} links={relationships.filter(r => r.playerAId === player.id || r.playerBId === player.id)} onDragStart={() => setDragged(player.id)} />)}</div></section>
    {simulations.filter(s => s.category === category).length ? <section className="xv-card"><h2 className="text-lg font-black">Simulações salvas</h2><div className="mt-3 flex flex-wrap gap-2">{simulations.filter(s => s.category === category).map(s => <button key={s.id} onClick={() => setState({ players, relationships, teams: s.teams as CampaoTeam[] })} className="rounded-xl border px-3 py-2 text-left text-sm"><b>{s.name}</b><br/><span className="text-[#6B7280]">{s.balanceScore}/100 · {new Date(s.updatedAt).toLocaleDateString("pt-BR")}</span></button>)}</div></section> : null}
    {!persistenceUnavailable ? <RelationshipPanel category={category} players={players} relationships={relationships} pending={isPending} run={startTransition} /> : null}
    <section className="xv-card"><h2 className="text-xl font-black">Times em construção</h2><p className="mt-1 text-sm text-[#6B7280]">Arraste cards para ajustar manualmente. Estatísticas e score são recalculados imediatamente.</p><div className="mt-4 grid gap-4 xl:grid-cols-3">{current.teams.map(team => { const stats = getCampaoTeamStats(current, team); return <article key={team.id} onDragOver={e => e.preventDefault()} onDrop={() => dragged && setState(moveCampaoPlayer(current, dragged, team.id))} className="rounded-2xl border border-[#E5E7EB] bg-[#FCFCFC] p-4"><div className="flex justify-between"><h3 className="font-black">{team.name}</h3><b>{stats.averageAge.toFixed(1)} anos</b></div><p className="mt-1 text-sm">A {stats.levelCounts.A} · B {stats.levelCounts.B} · C {stats.levelCounts.C} · D {stats.levelCounts.D} · E {stats.levelCounts.E}</p>{stats.issues.length ? <p className="mt-2 rounded-lg bg-[#FFF4E5] p-2 text-xs text-[#92400E]">{stats.issues.join(" • ")}</p> : <p className="mt-2 text-xs text-[#166534]">Composição completa</p>}<p className="mt-2 text-xs">Vínculos: {stats.satisfied.length} atendidos · {stats.broken.length} rompidos</p><div className="mt-3 space-y-2">{stats.players.map(p => <PlayerCard key={p.id} player={p} links={relationships.filter(r => r.playerAId === p.id || r.playerBId === p.id)} onDragStart={() => setDragged(p.id)} />)}</div></article> })}</div>
      {current.teams.length > 0 && <div onDragOver={e => e.preventDefault()} onDrop={() => dragged && setState(moveCampaoPlayer(current, dragged, null))} className="mt-4 rounded-xl border border-dashed p-3 text-sm text-[#6B7280]">Jogadores disponíveis: {players.filter(p => !assigned.has(p.id)).map(p => <span key={p.id} className="mr-2 inline-block"><PlayerCard player={p} links={relationships.filter(r => r.playerAId === p.id || r.playerBId === p.id)} onDragStart={() => setDragged(p.id)} /></span>)}</div>}</section>
  </div></main>;
}
function PlayerCard({ player, links, onDragStart }: { player: CampaoPlayer; links: CampaoRelationship[]; onDragStart: () => void }) { const title = links.map(l => `${relationshipTypeLabel[l.relationshipType] ?? l.relationshipType} • prioridade ${l.priorityWeight}`).join("\n"); return <div draggable onDragStart={onDragStart} title={title} className="cursor-grab rounded-xl border bg-white p-2 text-sm shadow-sm"><b>{player.fullName}</b>{links.length ? <span className="ml-2" aria-label="Possui vínculos">🔗</span> : null}<div className="mt-1 text-xs text-[#6B7280]">{player.age} anos · {positionLabel[player.position]} · nível {player.level ?? "não definido"}</div></div> }
function RelationshipPanel({ category, players, relationships, pending, run }: { category: CampaoCategory; players: CampaoPlayer[]; relationships: CampaoRelationship[]; pending: boolean; run: React.TransitionStartFunction }) { const [a,setA]=useState(""); const [b,setB]=useState(""); const [type,setType]=useState("FAMILY"); const [weight,setWeight]=useState(2); const [notes,setNotes]=useState(""); return <section className="xv-card"><h2 className="text-xl font-black">Vínculos entre jogadores</h2><form action={() => run(() => { void saveCampaoRelationship({category,playerAId:a,playerBId:b,relationshipType:type,priorityWeight:weight,notes}); setA("");setB("");setNotes(""); })} className="mt-3 grid gap-3 md:grid-cols-3"><select required value={a} onChange={e=>setA(e.target.value)} className="rounded-xl border p-2"><option value="">Jogador A</option>{players.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select required value={b} onChange={e=>setB(e.target.value)} className="rounded-xl border p-2"><option value="">Jogador B</option>{players.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border p-2">{Object.entries(relationshipTypeLabel).map(([value, label])=><option key={value} value={value}>{label}</option>)}</select><select value={weight} onChange={e=>setWeight(Number(e.target.value))} className="rounded-xl border p-2"><option value={1}>1 — Desejável</option><option value={2}>2 — Importante</option><option value={3}>3 — Obrigatório</option></select><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações (opcional)" className="rounded-xl border p-2"/><button disabled={pending || !a || !b || a===b} className="rounded-xl bg-[#B89020] p-2 font-bold text-white">Criar vínculo</button></form><div className="mt-4 space-y-2">{relationships.map(r => <div key={r.id} className="flex justify-between rounded-xl border p-3 text-sm"><span>{players.find(p=>p.id===r.playerAId)?.fullName} ↔ {players.find(p=>p.id===r.playerBId)?.fullName} · {relationshipTypeLabel[r.relationshipType] ?? r.relationshipType} · prioridade {r.priorityWeight}</span><button onClick={() => run(()=>{void deleteCampaoRelationship(r.id)})} className="text-[#B91C1C]">Excluir</button></div>)}</div></section> }
