"use client";
import { useMemo, useState, useTransition } from "react";
import { generateCampaoTeams, getCampaoBalanceScore, getCampaoTeamStats, type CampaoCategory, type CampaoPlayer, type CampaoRelationship, type CampaoState, type CampaoTeam } from "@/lib/campao-team-balancer";
import { deleteCampaoRelationship, saveCampaoRelationship, saveCampaoSimulation } from "./actions";

type Props = { persistenceUnavailable: boolean; players: (CampaoPlayer & { category: CampaoCategory })[]; relationships: (CampaoRelationship & { category: CampaoCategory })[]; simulations: { id: string; category: CampaoCategory; name: string; teams: unknown; balanceScore: number; updatedAt: string }[] };
const positionLabel: Record<string, string> = { GOLEIRO: "Goleiro", ZAGUEIRO: "Zagueiro", LATERAL: "Lateral", VOLANTE: "Volante", MEIA: "Meia", ATACANTE: "Atacante" };
const relationshipTypeLabel: Record<string, string> = { FATHER_AND_SON: "Pai e filho", BROTHERS: "Irmãos", FAMILY: "Família", FRIENDS: "Amigos", SPECIAL_REQUEST: "Pedido especial", OTHER: "Outro" };
export function CampaoSimulationClient({ persistenceUnavailable, players: allPlayers, relationships: allRelationships, simulations }: Props) {
  const [category, setCategory] = useState<CampaoCategory>("ADULTO"); const [isPending, startTransition] = useTransition();
  const [tab, setTab] = useState<"current" | "saved">("current");
  const players = useMemo(() => allPlayers.filter(p => p.category === category), [allPlayers, category]);
  const relationships = useMemo(() => allRelationships.filter(r => r.category === category), [allRelationships, category]);
  const [state, setState] = useState<CampaoState>({ players: allPlayers.filter(p => p.category === "ADULTO"), relationships: allRelationships.filter(r => r.category === "ADULTO"), teams: [] });
  const current = state.players === players ? state : { ...state, players, relationships };
  const score = getCampaoBalanceScore(current); const assigned = new Set(current.teams.flatMap(t => t.playerIds));
  const playersWithoutLevel = players.filter((player) => !player.level);
  function switchCategory(next: CampaoCategory) { setCategory(next); setTab("current"); setState({ players: allPlayers.filter(p => p.category === next), relationships: allRelationships.filter(r => r.category === next), teams: [] }); }
  const teamCount = 6;
  function save() { startTransition(() => { void saveCampaoSimulation({ category, name: `Simulação ${category === "ADULTO" ? "Adulto" : "Master"}`, teams: current.teams, statistics: current.teams.map(t => getCampaoTeamStats(current, t)), balanceScore: score }); }); }
  function loadSimulation(teams: unknown) { setState({ players, relationships, teams: teams as CampaoTeam[] }); setTab("current"); }
  function swapPlayers(firstId: string, secondId: string) { if (!firstId || !secondId || firstId === secondId) return; setState((previous) => ({ ...previous, teams: previous.teams.map((team) => ({ ...team, playerIds: team.playerIds.map((id) => id === firstId ? secondId : id === secondId ? firstId : id) })) })); }
  const savedSimulations = simulations.filter((simulation) => simulation.category === category);
  return <main className="xv-page-shell"><div className="xv-page-container space-y-5">
    <section className="xv-card"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8B6914]">Campeonato Interno XV Campão 2026</p><h1 className="mt-2 text-3xl font-black text-[#101010]">Simulação avançada de times</h1><p className="mt-2 max-w-3xl text-sm text-[#4B5563]">Geração multiobjetivo por posição, nível, idade e vínculos. Os cálculos ocorrem localmente; salve apenas as simulações que quiser manter.</p></div>
      <div className="mt-5 flex flex-wrap gap-2"><button onClick={() => switchCategory("ADULTO")} className={`rounded-xl px-4 py-2 font-bold ${category === "ADULTO" ? "bg-[#B89020] text-white" : "border"}`}>Adulto</button><button onClick={() => switchCategory("MASTER")} className={`rounded-xl px-4 py-2 font-bold ${category === "MASTER" ? "bg-[#B89020] text-white" : "border"}`}>Master</button><button disabled={playersWithoutLevel.length > 0} title={playersWithoutLevel.length ? "Defina o nível de todos os inscritos antes de sortear." : undefined} onClick={() => setState(generateCampaoTeams(current, teamCount))} className="ml-auto rounded-xl bg-[#101010] px-4 py-2 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Gerar nova simulação</button><button disabled={!current.teams.length} onClick={() => exportTeamsToCsv(current, category, relationships)} className="rounded-xl border border-[#166534] bg-white px-4 py-2 font-bold text-[#166534] disabled:cursor-not-allowed disabled:opacity-50">Exportar para Excel</button><button disabled={persistenceUnavailable || !current.teams.length || isPending} onClick={save} className="rounded-xl bg-[#B89020] px-4 py-2 font-bold text-white">Salvar simulação</button></div>
    </section>
    {persistenceUnavailable ? <div className="rounded-xl border border-[#FDBA74] bg-[#FFF7ED] px-4 py-3 text-sm text-[#9A3412]">A estrutura de persistência ainda não foi aplicada ao banco. A simulação pode ser usada, mas vínculos e simulações salvas só estarão disponíveis após a migration.</div> : null}
    {playersWithoutLevel.length > 0 ? <div className="rounded-xl border border-[#FDBA74] bg-[#FFF7ED] px-4 py-3 text-sm text-[#9A3412]">{playersWithoutLevel.length} {playersWithoutLevel.length === 1 ? "jogador está sem nível" : "jogadores estão sem nível"}. Eles aparecem na lista e podem receber vínculos, mas o sorteio fica liberado somente após classificar todos.</div> : null}
    <section className="grid gap-3 sm:grid-cols-4">{[["Jogadores de linha", players.filter(player => player.position !== "GOLEIRO").length], ["Goleiros", players.filter(player => player.position === "GOLEIRO").length], ["Times", `${teamCount} previstos`], ["Salvas", simulations.filter(s => s.category === category).length]].map(([l,v]) => <div key={String(l)} className="xv-card"><p className="text-xs font-bold uppercase text-[#6B7280]">{l}</p><p className="mt-1 text-2xl font-black">{v}</p></div>)}</section>
    <section className="xv-card"><div className="flex flex-wrap gap-2"><button onClick={() => setTab("current")} className={`rounded-xl px-4 py-2 font-bold ${tab === "current" ? "bg-[#101010] text-white" : "border"}`}>Última simulação</button><button onClick={() => setTab("saved")} className={`rounded-xl px-4 py-2 font-bold ${tab === "saved" ? "bg-[#101010] text-white" : "border"}`}>Times salvos ({savedSimulations.length})</button></div><p className="mt-3 text-sm text-[#6B7280]">Abra uma simulação salva para revisá-la e fazer trocas manuais; os indicadores são recalculados na hora.</p></section>
    <section className="xv-card"><h2 className="text-xl font-black">Inscritos da categoria</h2><p className="mt-1 text-sm text-[#6B7280]">A lista completa fica disponível para consulta e criação de vínculos, inclusive antes da classificação de nível.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{players.map(player => <PlayerCard key={player.id} player={player} players={players} links={relationships.filter(r => r.playerAId === player.id || r.playerBId === player.id)} />)}</div></section>
    {tab === "saved" ? <section className="xv-card"><h2 className="text-xl font-black">Times salvos</h2>{savedSimulations.length ? <div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{savedSimulations.map(s => <article key={s.id} className="rounded-2xl border border-[#E5E7EB] bg-[#FCFCFC] p-4"><b>{s.name}</b><p className="mt-1 text-sm text-[#6B7280]">Score {s.balanceScore}/100 · atualizado em {new Date(s.updatedAt).toLocaleDateString("pt-BR")}</p><button onClick={() => loadSimulation(s.teams)} className="mt-3 rounded-xl bg-[#B89020] px-3 py-2 text-sm font-bold text-white">Abrir para editar</button></article>)}</div> : <p className="mt-3 text-sm text-[#6B7280]">Nenhuma simulação salva nesta categoria.</p>}</section> : null}
    {!persistenceUnavailable ? <RelationshipPanel category={category} players={players} relationships={relationships} pending={isPending} run={startTransition} /> : null}
    {tab === "current" ? <section className="xv-card"><h2 className="text-xl font-black">Última simulação gerada</h2><p className="mt-1 text-sm text-[#6B7280]">Cada time deve ter 13 jogadores de linha; goleiros não entram nessa contagem.</p>{current.teams.length ? <SwapPlayersPanel state={current} onSwap={swapPlayers} /> : null}<div className="mt-4 grid gap-4 xl:grid-cols-3">{current.teams.map(team => { const stats = getCampaoTeamStats(current, team); return <article key={team.id} className="rounded-2xl border border-[#E5E7EB] bg-[#FCFCFC] p-4"><div className="flex justify-between"><h3 className="font-black">{team.name}</h3><b>{stats.averageAge.toFixed(1)} anos</b></div><p className="mt-1 text-sm">A {stats.levelCounts.A} · B {stats.levelCounts.B} · C {stats.levelCounts.C} · D {stats.levelCounts.D} · E {stats.levelCounts.E}</p>{stats.issues.length ? <p className="mt-2 rounded-lg bg-[#FFF4E5] p-2 text-xs text-[#92400E]">{stats.issues.join(" • ")}</p> : <p className="mt-2 text-xs text-[#166534]">Composição completa</p>}<p className="mt-2 text-xs">Vínculos: {stats.satisfied.length} atendidos · {stats.broken.length} rompidos</p><div className="mt-3 space-y-2">{stats.players.map(p => <PlayerCard key={p.id} player={p} players={players} links={relationships.filter(r => r.playerAId === p.id || r.playerBId === p.id)} />)}</div></article> })}</div>
      {current.teams.length > 0 && <div className="mt-4 rounded-xl border border-dashed p-3 text-sm text-[#6B7280]">Jogadores disponíveis: {players.filter(p => !assigned.has(p.id)).map(p => <span key={p.id} className="mr-2 inline-block"><PlayerCard player={p} players={players} links={relationships.filter(r => r.playerAId === p.id || r.playerBId === p.id)} /></span>)}</div>}</section> : null}
  </div></main>;
}
function PlayerCard({ player, players, links }: { player: CampaoPlayer; players: CampaoPlayer[]; links: CampaoRelationship[] }) { const relationshipDetails = links.map(link => { const relatedPlayerId = link.playerAId === player.id ? link.playerBId : link.playerAId; const relatedPlayer = players.find(candidate => candidate.id === relatedPlayerId); return `${relationshipTypeLabel[link.relationshipType] ?? link.relationshipType}: ${relatedPlayer?.fullName ?? "jogador não encontrado"}`; }); const title = relationshipDetails.join("\n"); return <div title={title} className="select-text rounded-xl border bg-white p-2 text-sm shadow-sm"><b>{player.fullName}</b>{links.length ? <span className="ml-2" aria-label="Possui vínculos">🔗</span> : null}<div className="mt-1 text-xs text-[#6B7280]">{player.age} anos · {positionLabel[player.position]} · nível {player.level ?? "não definido"}</div><div className="mt-1 text-xs text-[#6B7280]">Telefone: {player.phone || "não informado"}</div>{player.adminNotes ? <div className="mt-2 whitespace-pre-wrap rounded-lg bg-[#F3F4F6] px-2 py-1 text-xs text-[#374151]">Obs.: {player.adminNotes}</div> : null}{relationshipDetails.length ? <div className="mt-2 rounded-lg bg-[#FFF9EA] px-2 py-1 text-xs font-semibold text-[#70520B]">Vínculo: {relationshipDetails.join(" · ")}</div> : null}</div> }
function SwapPlayersPanel({ state, onSwap }: { state: CampaoState; onSwap: (firstId: string, secondId: string) => void }) { const [firstId, setFirstId] = useState(""); const [secondId, setSecondId] = useState(""); const options = state.teams.flatMap((team) => team.playerIds.map((playerId) => ({ team: team.name, player: state.players.find((item) => item.id === playerId)! }))).filter((item) => item.player); return <div className="mt-4 grid gap-3 rounded-2xl border border-[#D1D5DB] bg-[#F8FAFC] p-4 md:grid-cols-3"><div className="md:col-span-3"><h3 className="font-black">Trocar jogadores entre times</h3><p className="mt-1 text-sm text-[#6B7280]">A troca preserva a quantidade de atletas e recalcula os indicadores de todos os times.</p></div><select value={firstId} onChange={(event) => setFirstId(event.target.value)} className="rounded-xl border border-[#CBD5E1] bg-white p-3 text-sm"><option value="">Primeiro jogador</option>{options.map(({ team, player }) => <option key={player.id} value={player.id}>{team} — {player.fullName}</option>)}</select><select value={secondId} onChange={(event) => setSecondId(event.target.value)} className="rounded-xl border border-[#CBD5E1] bg-white p-3 text-sm"><option value="">Segundo jogador</option>{options.map(({ team, player }) => <option key={player.id} value={player.id}>{team} — {player.fullName}</option>)}</select><button disabled={!firstId || !secondId || firstId === secondId} onClick={() => { onSwap(firstId, secondId); setFirstId(""); setSecondId(""); }} className="rounded-xl bg-[#B89020] px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Trocar jogadores</button></div>; }
function exportTeamsToCsv(state: CampaoState, category: CampaoCategory, relationships: CampaoRelationship[]) { const escape = (value: string | number | null | undefined) => `"${String(value ?? "").replace(/"/g, '""')}"`; const rows: Array<Array<string | number>> = [["Categoria", "Time", "Média de idade", "Jogadores de linha", "Goleiros", "Nível A", "Nível B", "Nível C", "Nível D", "Nível E", "Jogador", "Idade", "Posição", "Nível", "Telefone", "Observações administrativas", "Vínculos"]]; state.teams.forEach((team) => { const stats = getCampaoTeamStats(state, team); stats.players.forEach((player) => { const links = relationships.filter((relationship) => relationship.playerAId === player.id || relationship.playerBId === player.id).map((relationship) => { const relatedId = relationship.playerAId === player.id ? relationship.playerBId : relationship.playerAId; const related = state.players.find((candidate) => candidate.id === relatedId); return `${relationshipTypeLabel[relationship.relationshipType] ?? relationship.relationshipType}: ${related?.fullName ?? "jogador não encontrado"}`; }).join(" · "); rows.push([category === "ADULTO" ? "Adulto" : "Master", team.name, stats.averageAge.toFixed(1), stats.players.filter((item) => item.position !== "GOLEIRO").length, stats.positions.GOLEIRO, stats.levelCounts.A, stats.levelCounts.B, stats.levelCounts.C, stats.levelCounts.D, stats.levelCounts.E, player.fullName, player.age, positionLabel[player.position], player.level || "Não definido", player.phone, player.adminNotes || "", links]); }); }); const csv = `\uFEFF${rows.map((row) => row.map(escape).join(";")).join("\n")}`; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `times-${category.toLowerCase()}-campao-2026.csv`; link.click(); URL.revokeObjectURL(url); }
function RelationshipPanel({ category, players, relationships, pending, run }: { category: CampaoCategory; players: CampaoPlayer[]; relationships: CampaoRelationship[]; pending: boolean; run: React.TransitionStartFunction }) { const [a,setA]=useState(""); const [b,setB]=useState(""); const [type,setType]=useState("FAMILY"); const [weight,setWeight]=useState(2); const [notes,setNotes]=useState(""); return <section className="xv-card"><h2 className="text-xl font-black">Vínculos entre jogadores</h2><form action={() => run(() => { void saveCampaoRelationship({category,playerAId:a,playerBId:b,relationshipType:type,priorityWeight:weight,notes}); setA("");setB("");setNotes(""); })} className="mt-3 grid gap-3 md:grid-cols-3"><select required value={a} onChange={e=>setA(e.target.value)} className="rounded-xl border p-2"><option value="">Jogador A</option>{players.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select required value={b} onChange={e=>setB(e.target.value)} className="rounded-xl border p-2"><option value="">Jogador B</option>{players.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border p-2">{Object.entries(relationshipTypeLabel).map(([value, label])=><option key={value} value={value}>{label}</option>)}</select><select value={weight} onChange={e=>setWeight(Number(e.target.value))} className="rounded-xl border p-2"><option value={1}>1 — Desejável</option><option value={2}>2 — Importante</option><option value={3}>3 — Obrigatório</option></select><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações (opcional)" className="rounded-xl border p-2"/><button disabled={pending || !a || !b || a===b} className="rounded-xl bg-[#B89020] p-2 font-bold text-white">Criar vínculo</button></form><div className="mt-4 space-y-2">{relationships.map(r => <div key={r.id} className="flex justify-between rounded-xl border p-3 text-sm"><span>{players.find(p=>p.id===r.playerAId)?.fullName} ↔ {players.find(p=>p.id===r.playerBId)?.fullName} · {relationshipTypeLabel[r.relationshipType] ?? r.relationshipType} · prioridade {r.priorityWeight}</span><button onClick={() => run(()=>{void deleteCampaoRelationship(r.id)})} className="text-[#B91C1C]">Excluir</button></div>)}</div></section> }
