ALTER TYPE "ChampionshipPlayerStatus" ADD VALUE IF NOT EXISTS 'BIONICO';

ALTER TABLE "Match"
  ALTER COLUMN "homeScore" DROP DEFAULT,
  ALTER COLUMN "homeScore" DROP NOT NULL,
  ALTER COLUMN "awayScore" DROP DEFAULT,
  ALTER COLUMN "awayScore" DROP NOT NULL;
